### ISSUE TITLE
Tags page inside admin panel should have the same design as the sidebar

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#103]
**Describe the bug**
The tags listing should have the same design as the design at the sidebar of the tags.

**To Reproduce**
1. Go to administration
2. Click on tags
3. See error

**Expected behavior**
The tag color boxes should have less border-radius and should have a box-shadow underneath it.

**Screenshots**
![screenshot_2018-07-29 extum material theme demo 4](https://user-images.githubusercontent.com/17576065/43361503-a7f94cf8-92d8-11e8-9840-22a2718025a8.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version: 0.1.0-beta.7

**Comment by ghost** [comment]
I forgot to add those, I'll add 2PX border radius with shadow tonight or tomorrow, when I have time.
