### ISSUE TITLE
Arrangement issue on user list by ReFlar

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#104]
**Describe the bug**
User list by ReFlar extension list has an arrangement issue that needs to be fixed.

**To Reproduce**
1. Go to administration
2. Click on users (user list)
3. See error

**Expected behavior**
The list should items should be centered.

**Screenshots**
![123048712834](https://user-images.githubusercontent.com/17576065/43361524-34d9cc88-92d9-11e8-85a0-39de4ab5e86f.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version: 0.1.0-beta.7

**Comment by ghost** [comment]
Don't assign everything to me.

**Comment by ardacebi** [comment]
@Nathan2023 I'm assigning you to only the padding stuff.

**Comment by ghost** [comment]
Ok thanks.
