### ISSUE TITLE
Links item arrangement issue

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#105]
**Describe the bug**
Links list items are not arranged well.

**To Reproduce**
1. Go to administration
2. Click on links
3. See error

**Expected behavior**
The pen icon and the link title should be at the same level.

**Screenshots**
![links](https://user-images.githubusercontent.com/17576065/43361555-13a8db7a-92da-11e8-915c-e95300712a26.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version: 0.1.0-beta.7

**Comment by ghost** [comment]
Btw, the Orange Line is not seen on Chrome however, I will take a look into that.

**Comment by ardacebi** [comment]
😂😂😂

**Comment by ghost** [comment]
Oh wait xD, that's you showing how it's supposed to be LOL

**Comment by ardacebi** [comment]
Yes obviously. All red/orange/blue lines you will see around this repo is done by me. (Yes, the colors do change depending on which software I'm using to put them on)

**Comment by ghost** [comment]
I was literally just gonna tell you to open a PR to fix it... This is so sad 😂

**Comment by ardacebi** [comment]
If you're assigned you should be the one doing it. I have my own assigned work.

**Comment by ghost** [comment]
No, I was gonna say open a PR for the Orange line 😂

**Comment by ardacebi** [comment]
Yes, I understood that. Even if the issue was that you should be the one working on.
