### ISSUE TITLE
Notification dropdown issue

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#108]
![screenshot_2018-07-29 localflar 4](https://user-images.githubusercontent.com/17576065/43370584-1bf995c0-938a-11e8-8d22-0965480f300e.png)

Started happening with the recent commits.

**Comment by ghost** [comment]
Can you explain more what's going on?

**Comment by ardacebi** [comment]
@Nathan2023 Recent commits caused an issue where the dropdowns do not expand to the left side but right side getting out of the screen

**Comment by ghost** [comment]
I'll take a look more into it.

**Comment by ghost** [comment]
Is this only in Colored Header?

**Comment by ardacebi** [comment]
Nope, colored header issues are tagged and mentioned on the issue title.

**Comment by ardacebi** [comment]
By the way, you can't reproduce the issue on the demo server, I'm now working on the local server.

Uninstall and re-install the extension on your local installation to see it.

```
composer remove extum/flarum-ext-material && composer require extum/flarum-ext-material:dev-development
```

**Comment by Nathan2023** [comment]
Ok.

**Comment by ghost** [comment]
This is fixed with the latest commit!
