### ISSUE TITLE
Tooltips on hover for group badges (permissions page)

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#115]
![screenshot_2018-07-30 localflar 3](https://user-images.githubusercontent.com/17576065/43404069-46405734-941f-11e8-8332-31e37cd76ef9.png)

Tooltips with the names of the groups should be displayed under the badges if the user hovers over one of them.

**Comment by hammerhai** [comment]
I'll take a look into this, but it's not a priority in 0.1.0-beta.12.

Issue will be closed.
