### ISSUE TITLE
ExtensionListItem more button issue

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#116]
Because ".Button" has a box-shadow defined in the style file, all buttons start having box-shadows. This caused an issue on the ExtensionListItem card.

![1342342134](https://user-images.githubusercontent.com/17576065/43419313-3ffdd61a-9449-11e8-8f4e-3d7928a7c509.png)

**Comment by ghost** [comment]
Looking into it.

**Comment by ghost** [comment]
Fixing now.
