### ISSUE TITLE
MDL to MDC with ripple effects

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#117]
Switch from MDL to MDC supporting ripple effects.

- [ ] Buttons
- [ ] Switches
- [ ] Ripples
- [ ] Dropdowns
- [ ] Loaders
- [ ] Tooltips
- [ ] Dialogs
- [ ] Checkboxes
- [ ] Radio Buttons
- [ ] Snackbars

**Comment by hammerhai** [comment]
Using some jQuery we can actually change the classes of an element, an element with id, and element with a class, or an element with a specified pseudo-class.

```
$("button").addClass("className");
```

Or for multiple classes.

```
$("button").addClass("className className2");
// Separate by spaces
```

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.

All of this will be in the roadmap coming for 0.1.0-beta.12-13
