### ISSUE TITLE
Materializing newDiscussion button by making it a FAB

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#12]
https://getmdl.io/components/index.html#buttons-section

**Comment by ardacebi** [comment]
@PartialDevAdmin Why an extension? Isn't it possible to move the button to bottom right, giving it a round box shadow and changing the text without an extension and just CSS?

**Comment by ghost** [comment]
I'll see what I can do

**Comment by hammerhai** [comment]
Can you move this issue to one without a planned release until the future and after this has been discussed. Thank you.

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.
