### ISSUE TITLE
Admin panel active tab icon bold issue

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#120]
If a tab section is selected (active) at the admin panel, the Material icon for it gets too bold and becomes invisible. This effect should be removed.

**Comment by ardacebi** [comment]
@PartialDevAdmin @TristianK3604 Can this be a core issue?

**Comment by ghost** [comment]
I'll take a look.

**Comment by ghost** [comment]
This has been successfully added, can be tested on the Demo Forum!
