### ISSUE TITLE
Extension icon fix issues

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#122]
https://github.com/Extum/flarum-ext-material/commit/6cc8253489c3b32c5924086a04e674832a50c7da caused some size issues on other icons.

![screenshot_2018-08-01 extum](https://user-images.githubusercontent.com/17576065/43538225-16283f2e-95ca-11e8-93ab-147511bfa3b8.png)

![screenshot_2018-08-01 extum 1](https://user-images.githubusercontent.com/17576065/43538227-179d42a0-95ca-11e8-94a9-1785c6eb05a0.png)

Maybe more?

@PartialDevAdmin @TristianK3604 Is there any way we can apply that change only to the extension items area instead of the whole admin.less file?

I did this on purpose and I don't want to undo this change, the icons on the extensions look great, we just have to find a way to apply that only to that area.

**Comment by ghost** [comment]
Looks like the big guy wants to run.

**Comment by ardacebi** [comment]
This is no longer valid because of Beta 8 thingy.
