### ISSUE TITLE
Not sure if this is the correct icon for the side menu

### ISSUE THREAD

**Issue by mikejones3** [Extum/material#126]
Instead of the 3 dots should it not be the hamburger 3 line icon?

This is the icon I think is not incorrect:

https://imgur.com/ZR3qIZI

**Comment by ardacebi** [comment]
Can you send a screenshot you didn't crop? For me to understand where is that.

**Comment by ghost** [comment]
Its when you move over to the left when you are on a discussion, the little bar slides out from the left, @TurboProgramming

**Comment by mikejones3** [comment]
@TurboProgramming here is a non cropped image:

https://imgur.com/rvB1z6L

**Comment by ardacebi** [comment]
![screenshot_2018-08-02 hello world - extum material theme demo](https://user-images.githubusercontent.com/17576065/43570125-33898898-9642-11e8-9a97-21339a0d5079.png)

I don't have it on Firefox, but I see it on Chrome.

Seems like a Chrome issue.

**Comment by ghost** [comment]
Opening PR now which should fix this.
