### ISSUE TITLE
Design Suggestion: 3 dots do not need drop shadow on each post

### ISSUE THREAD

**Issue by mikejones3** [Extum/material#127]
If you look at each persons reply the 3 dot icon pops up with a drop shadow:

https://imgur.com/a/vriJZCn

To me this looks inconsistent, I would just have it pop up and match the "Like" and "Reply" buttons and maybe just change the color. The drop shadow is overused here and not needed.

**Comment by ardacebi** [comment]
The 3-dot button is connected to the `.Button` class and `.Button` has the drop-shadow. 

I'll see what I can do after the switch to MDL to MDC.

**Comment by ghost** [comment]
I'll take a look.

**Comment by ghost** [comment]
This has been successfully completed and can be tested on the Demo Forum!
