### ISSUE TITLE
Cosmetic - Discussion List/Comment list in a discussion

### ISSUE THREAD

**Issue by Madchatthew** [Extum/material#128]
**Is your feature request related to a problem? Please describe.**
This is not related to a problem. 

**Describe the solution you'd like**
To me it would look better if the discussion list and the comments in a discussion looked the same. Currently the comments when you click on a discussion has a nice space and shadow effect separating the comments. I like that look. This css change would propose that the discussion list on the main page would look the same.

**Describe alternatives you've considered**
To leave it as is, although cosmetically I think it would look more unified.

**Additional context**
Current look:

![image](https://user-images.githubusercontent.com/24220452/43699352-0d57bd78-9914-11e8-9e56-df014023cfd5.png)

Proposed change:

![image](https://user-images.githubusercontent.com/24220452/43699422-4bebe2da-9914-11e8-96ba-2b370d4d38c7.png)

The css code: 
Location: flarum-ext-material\resources\less\app.less

// Original

.DiscussionList-discussions {
  list-style-type:none;
  position:relative;
  box-shadow: @default-shadow;
  transition: all 0.3s cubic-bezier(.25,.8,.25,1);
  padding-left: 15px;
  margin-top: 20px;
  border-radius: 2px;
}

 --Change
 .DiscussionList-discussions {
   list-style-type:none;
   position:relative;
   transition: all 0.3s cubic-bezier(.25,.8,.25,1);
   padding-left: 15px;
   margin-top: 20px;
   border-radius: 2px;
 }

// Original

.DiscussionListItem {
  position:relative;
  margin-right:0px;
  padding-right:25px;
  padding-left:15px;
  margin-left:-15px;
  border-radius: 2px;
  transition:background .2s;
  }

// change

.DiscussionListItem {
  position:relative;
  margin-right:0px;
  padding-right:25px;
  padding-left:15px;
  margin-left:-15px;
  border-radius: 2px;
  transition:background .2s;
  margin-bottom: 15px;
  box-shadow: 0 2px 3px rgba(0,0,0,0.12),0 1px 2px rgba(0,0,0,0.24);
}

**Comment by ardacebi** [comment]
Can you open a pull request so we can discuss this there and merge if we agree?

Thanks for offering this idea, I kinda like it too.

**Comment by Madchatthew** [comment]
Hey Arda,

I have tried to open a pull request and not sure which options I should
choose. Do I need to create a branch so I can make a pull request on for
that part and compare the changes? Or which two branches do I choose?

Thanks for your help.

**Comment by ardacebi** [comment]
https://github.com/Extum/flarum-ext-material/blob/development/resources/less/app.less#L621-L629

https://github.com/Extum/flarum-ext-material/blob/development/resources/less/app.less#L631-L639

Here are the lines you wanted to apply changes on, click on each one to go the lines, you can click the edit icon at the top of the file (page) and replace those lines, then click on propose/commit changes. 

You will then see the create a new pull request button, click on that, add a title, description and any extra information that may help us with it.

---

This should open the PR and we will start discussing it there.
