### ISSUE TITLE
Bug on check and refresh button

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#13]
![screenshot_2018-07-26 extum material theme demo 3](https://user-images.githubusercontent.com/17576065/43265818-8a7288d0-90f2-11e8-8251-a2b3767e68cb.png)

Should be centered

**Comment by ghost** [comment]
This has been centered and is being changed now.

**Comment by ardacebi** [comment]
PR?

**Comment by ardacebi** [comment]
Didn't work.

**Comment by ghost** [comment]
This **should** be fixed in the new release of bug fixes, and will also fix every button with (Only) an Icon that is not currently centered.

**Comment by ardacebi** [comment]
This is not fixed with your PR.

**Comment by ghost** [comment]
Ok, I think it's a Padding issue.

**Comment by TurboProgramming** [comment]
https://github.com/Extum/flarum-ext-material/commit/17680a00d2f9fe5fa44a7720fe979478860d7d12 makes this PR better.
