### ISSUE TITLE
Version number getting outside of the card

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#137]
![schermata 2018-08-11 alle 01 57 29](https://user-images.githubusercontent.com/17576065/43984573-066185a4-9d0a-11e8-9b2d-11f955eace1a.png)

If the version number is long, it should be replaced with ... at the end like the name.

**Comment by ghost** [comment]
I stated that in the PR from earlier, and I am working on a fix.

**Comment by ghost** [comment]
This has become worse with the latest commits, I know where it's coming from as most buttons have this issue now. 

**Anyone who sees this issue and has the latest version from just a few minutes ago, please downgrade to your previous version until fixed!**

Commit: https://github.com/Extum/flarum-ext-material/commit/3c22ce155d4efe5762fd6ceda0a21f1b741cd162 is causing this. Will be reviewed Aug 8, 2018.

**Comment by ghost** [comment]
Is this fixed with ßeta 8?

**Comment by ardacebi** [comment]
@Nathan2023 Yeah, I need to redesign this screen when we hit Beta 8 and that will fix this issue.
