### ISSUE TITLE
Inverse transition required for hovers

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#138]
We have a transition for the beginning hovers but we also need transitions for the end ones.

You can understand that there is no animation when you. stop hovering the extension icons and there is when you start hovering on them:

![registrazione schermo 2018-08-11 alle 01 59 45](https://user-images.githubusercontent.com/17576065/43984688-bc84c0c6-9d0a-11e8-8fac-4128b2b79496.gif)

**Comment by ghost** [comment]
I'll take a look at it tomorrow **(Aug 11, 2018)**.

**Comment by hammerhai** [comment]
I understand what you're seeing now. 

I can take a look right now.

Edit: Take a look tomorrow.

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.
