### ISSUE TITLE
Remove sliders

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#139]
![screenshot_2018-08-11 extum material theme demo 10](https://user-images.githubusercontent.com/17576065/43984724-fb761d48-9d0a-11e8-9ac5-ac89462bbab8.png)

![screenshot_2018-08-11 extum material theme demo 11](https://user-images.githubusercontent.com/17576065/43984733-165c9ba0-9d0b-11e8-967b-5ff222f0b9d5.png)

There are these sliders that are needed to be removed for them to look Material.

(Image 1: Admin panel)
(Image 2: iPad mini screenshot, make Chrome windows smaller and see that view)

**Comment by ghost** [comment]
I'm pretty sure I'm gonna have fun with this now 🤣, especially with the latest commits I have to fix.

**Comment by ardacebi** [comment]
Forget about this.
