### ISSUE TITLE
Restrict by tag button hover animation issue

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#140]
What it is now:

![registrazione schermo 2018-08-11 alle 02 09 58](https://user-images.githubusercontent.com/17576065/43984866-055a891a-9d0c-11e8-9b3b-26f856fccab8.gif)

Example of what it should be:

![registrazione schermo 2018-08-11 alle 02 10 20](https://user-images.githubusercontent.com/17576065/43984869-0aa93902-9d0c-11e8-8066-8424eda48f09.gif)

**Comment by Nathan2023** [comment]
This is because, multiple buttons had shadows which weren't supposed to contain shadows and they've been removed (for now).

**Comment by KodedScorpius** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.
