### ISSUE TITLE
Support for new extension page

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#149]
The extension page design will be changed with Beta 8, so we need to have support for it.

![screenshot_2018-08-23 localcomp](https://user-images.githubusercontent.com/17576065/44492963-ff9ea300-a66e-11e8-96ea-dbb90334bc49.png)

**Comment by KodedScorpius** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.
