### ISSUE TITLE
Fix for permissions/admin page

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#15]
![screenshot_2018-07-23 flightsimtr - havacilik forumu 1](https://user-images.githubusercontent.com/17576065/43075925-0c761398-8e8b-11e8-81a7-ffbb266060b0.png)

This page looks messed up 😬

**Comment by ghost** [comment]
I noticed this issue, with the Fixes branch I opened but, worse 🤣 Will be fixed shortly, remember, it's only a Super Mega Ultra Unstable release.

**Comment by ghost** [comment]
Working on this now.

**Comment by ghost** [comment]
I've set it to Medium as you can still use the Admin Panel and it works fine but, this will be fixed this year during development.
