### ISSUE TITLE
Device Compatibility

### ISSUE THREAD

**Issue by ghost** [Extum/material#150]
- [ ] Mobile Compatiblity (Devices with max-width view-port of 360px - Extra Small)
- [ ] Mobile and Tablet Compatiblity (Devices with min-width view-port of 361px and max-width of 768px - Small)
- [ ] Tablet Compatiblity (Devices with min-width view-port of 769px and max-width of 1024px - Medium)
- [ ] Laptop Compatiblity (Devices with min-width view-port of 1025px and max-width of 1280px - Large)
- [ ] Desktop Compatiblity (Devices with min-width view-port of 1281px - Extra Large)

**This is expected to be released in the middle of `1.0.0-beta.4` but, will be completely finished by the end of `1.0.0-beta.5`** (Do **NOT** remove the Milestone for `1.0.0-beta.5`)

**Comment by Nathan2023** [comment]
Issues to be fixed:

- [ ] Mobile, Tablet, & Laptop https://github.com/Extum/flarum-ext-material/issues/51
- [x] Mobile, & Tablet https://github.com/Extum/flarum-ext-material/issues/97
- [x] Mobile, Tablet, Laptop, & Desktop https://github.com/Extum/flarum-ext-material/issues/94

More coming soon...

**Comment by KodedScorpius** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.

Flarum has it's own grid, past Nathan.
