### ISSUE TITLE
[Dark Mode] Profile menu dropdown color issue

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#152]
Dropdown looks like this on dark mode:

![screenshot_2018-08-24 extum material theme demo 2](https://user-images.githubusercontent.com/17576065/44584682-6bd5ef80-a7b2-11e8-8f50-23a4b485c052.png)

**Comment by ardacebi** [comment]
These too:

![screenshot_2018-08-24 extum material theme demo 3](https://user-images.githubusercontent.com/17576065/44584718-86a86400-a7b2-11e8-9d25-5f450ffe85fb.png)

**Comment by ardacebi** [comment]
and this...

![screenshot_2018-08-24 extum material theme demo 4](https://user-images.githubusercontent.com/17576065/44584732-93c55300-a7b2-11e8-93ba-5c825906c308.png)

**Comment by ardacebi** [comment]
![screenshot_2018-08-24 extum material theme demo 5](https://user-images.githubusercontent.com/17576065/44584786-bd7e7a00-a7b2-11e8-846f-c68034217a16.png)

**Comment by MeteorCoder** [comment]
It seems this may actually be a Core issue because there is NO tag on the menus to show they're in DM. So you'd have to iverwrite the dark content but, I'm unsure how.

**Comment by KodedScorpius** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.
