### ISSUE TITLE
Separator issue on notification settings table

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#18]
https://github.com/Extum/flarum-theme-material/blob/72d87af5da67090ff6258aef93cecca0d1475ea0/material.css#L392

![screenshot_2018-07-23 ayarlar - flightsimtr - havacilik forumu](https://user-images.githubusercontent.com/17576065/43088701-80c0036a-8eab-11e8-89f0-cd0d6fd74aff.png)

Separator disappears when arrives to titles with icons.

**Comment by ghost** [comment]
I'll take a look into this issue.
