### ISSUE TITLE
Better and visible color selection needed

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#19]
https://github.com/Extum/flarum-theme-material/blob/e98e3a367fab4d2088e6be73bb936b81f5eb222a/material.css#L496

Current color (whitesmoke) is not visible as well.

**Comment by ghost** [comment]
What element is the `background` needed for in the CSS for line `#496` @TurboProgramming?

**Comment by ardacebi** [comment]
@PartialDevAdmin Yes, if you're good at color selection. The current color looks invisible.

It should not be so black, and white either. Grey didn't work so I'm leaving this to you for a PR.

**Comment by ardacebi** [comment]
> What element is the background needed for in the CSS for line #496 @TurboProgramming?

We need another color for it to look visible. WhiteSmoke doesn't work well.

**Comment by meetdilip** [comment]
This ? #e0e9c3

**Comment by ardacebi** [comment]
@meetdilip Can you get the focus color of the forum and apply a filter on it to be lighter like the color you sent me?

**Comment by meetdilip** [comment]
What is focus colour ?
