### ISSUE TITLE
Issue on reply & follow buttons

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#20]
![screenshot_2018-07-23 rejected takeoff - kalkis iptal etme - flightsimtr - havacilik forumu](https://user-images.githubusercontent.com/17576065/43089224-c797ee00-8eac-11e8-98fd-2f4088eae950.png)

Reply and follow buttons inside discussion pages are misaligned.

**Comment by ghost** [comment]
Ok, I've fixed the follow button issue however, the Admin button you have to find a fix for yourself as I don't have it.

**Comment by ardacebi** [comment]
![screenshot_2018-07-24 ucus kontrol kumanda yuzeyleri - flightsimtr - havacilik forumu](https://user-images.githubusercontent.com/17576065/43133767-70200e5e-8f48-11e8-9a0d-714bc3a7c142.png)

This looks messed up with your PR.
