### ISSUE TITLE
Switches not working

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#21]
https://github.com/Extum/flarum-theme-material/blob/e98e3a367fab4d2088e6be73bb936b81f5eb222a/material.css#L171

Even if we applied switch styles from getmdl.io, switches are not working.

It is possible that `.Checkbox-display` is not valid, because we also saw only `.Checkbox` while browsing the css file but both didn't work for the theme.

**Comment by ghost** [comment]
Actually I can add a specific class to the CSS file, and make it seem like it's by MDL  and just style it the way it looks.

**Comment by ghost** [comment]
I've updated the CSS to include this fix!

**Comment by ardacebi** [comment]
Thank you @Nathan2023.
