### ISSUE TITLE
Log in button text not Vertically Aligned

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#43]
![screenshot_2018-07-24 devsland forum](https://user-images.githubusercontent.com/17576065/43152312-ef4b51c4-8f76-11e8-9e8c-65a5f0dc9d53.png)

Log in button text should be centered. The CSS below is it's Flarum's original style gathered from the inspector.

```
.Button--block,.LogInButton {
 display:block;
 width:100%;
 overflow:hidden;
 text-overflow:ellipsis;
}
```

**Comment by meetdilip** [comment]
It was a padding issue. Try this

`.Form--centered .FormControl[type="text"], .Form--centered .FormControl[type="email"], .Form--centered .FormControl[type="password"], .Form--centered .Button {
    margin: 10px;
    text-align: center;
    height: 50px;
    padding: 0px20px;
    font-size: 15px;
}`

padding earlier was 15px 20px. Changed 15px to 0px

**Comment by meetdilip** [comment]
Here is the output

![login button flarum material](https://user-images.githubusercontent.com/6965443/43153340-aad7e792-8f8e-11e8-93a9-c71b4497851f.jpg)

**Comment by ardacebi** [comment]
@meetdilip I don't have time for editing, can you open a PR so I will merge it later?

**Comment by meetdilip** [comment]
I am not sure where to add. Simply include the above code in material.css ?

**Comment by ardacebi** [comment]
@meetdilip I added the code above at the bottom of the material.css but it didn't change anything. I have the code below on the style file maybe it's because of that?

https://github.com/Extum/flarum-theme-material/blob/4e7921b802e54a27a5768715851d9e30399eef38/material.css#L519

**Comment by meetdilip** [comment]
I am a bit out of touch. Which part of file overwrites other entries ? Top or bottom ?

@TurboProgramming  possible.

**Comment by ardacebi** [comment]
Top

**Comment by meetdilip** [comment]
Shall I add it there then ?

**Comment by ardacebi** [comment]
Do it. I'll try on the demo forum and see how it will look.

**Comment by meetdilip** [comment]
Done :)

**Comment by ardacebi** [comment]
@PartialDevAdmin I just created a new demo server dedicated for the theme, feel free to test post and play around. https://materialtheme.freeflarum.com/
