### ISSUE TITLE
Visual bug on app bar

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#47]
e2cbb3c caused an issue that on some screens, the shadow looking good on the main screen doesn't look good on colored areas such as user profiles or colored tag pages.

![screenshot_2018-07-25 ayarlar - flightsimtr - havacilik forumu](https://user-images.githubusercontent.com/17576065/43168108-b218c5ba-8fa4-11e8-99a7-2bfec5d721d2.png)

A solution is necessary for this **without the removal** of the shadow from the app bar as it's necessary according to Material guidelines.

**Comment by ghost** [comment]
Will take a look into this issue.

**Comment by ghost** [comment]
I've found the code that is causing this issue and fixing it right now.
