### ISSUE TITLE
[Mobile] Topic links are not clickable from all discussions list

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#48]
When you attempt clicking to a topic link from the discussion list, nothing will happen (including shadows changes, color changes etc.)

Other links such as settings, profile are not working strangely. Although this needs confirmation, can someone else confirm this too?

**Comment by ghost** [comment]
All have been confirmed and I will look into.

**Comment by ghost** [comment]
Located issue, fixing now.

**Comment by ghost** [comment]
I'm now noticing from Mobile you cannot click the discussions as described. Let me check all possible causes.

**Comment by ghost** [comment]
Suddenly links have been fixed, IDK by what while I was inspecting but, they were.. Let me track the changes back.

**Comment by ghost** [comment]
This most likely was caused by the Selection Menu not working properly. Reopen if issue continues after PRs are approved!
