### ISSUE TITLE
[Mobile] Author profile picture shadows not displayed correctly on all discussions list

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#49]
Author profile pictures and shadows are not displayed well compared to the desktop version on mobile devices.

![image2](https://user-images.githubusercontent.com/17576065/43168353-a7dedae8-8fa5-11e8-8a55-d04483394699.jpeg)

**Comment by meetdilip** [comment]
```
.DiscussionListItem-author {
    float: left;
    margin-top: 13px;
    transition: all .3s cubic-bezier(.25, .8, .25, 1);
    background: radial-gradient(circle at center 75px, transparent, transparent 50px);
    -webkit-filter: drop-shadow(0px 2px 2px #808080);
    overflow: hidden;
}
```
drop-shadow part defines it. We can make the colour #000 to make it distinct shadow

**Comment by meetdilip** [comment]
```.DiscussionListItem-author {    float: left;    margin-top: 13px;    transition: all .3s cubic-bezier(.25, .8, .25, 1);    background: radial-gradient(circle at center 75px, transparent, transparent 50px);    -webkit-filter: drop-shadow(0px 2px 2px #808080);    overflow: hidden;}```

**Comment by meetdilip** [comment]
I haven't changed any code from the default. I was just pointing out where to fix. To be honest, I was not sure what to fix.

**Comment by ardacebi** [comment]
@meetdilip I think it's not shadow related. It's something with the layout, the shadow makes it look bad. Changing the shadow color won't fix this.

**Comment by ghost** [comment]
Check to see if this is fixed with both the Stable and Developmental branch.

**Comment by ardacebi** [comment]
This issue should be fixed with the latest commits.
