### ISSUE TITLE
[Mobile] Buttons on sidebar not displayed correctly

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#50]
Buttons on the sidebar (links) are not displayed correctly on mobile devices.

![screenshot_2018-07-25 flightsimtr - havacilik forumu 2](https://user-images.githubusercontent.com/17576065/43169199-e6661c88-8fa8-11e8-9436-2db3e1fec91b.png)

**Comment by ghost** [comment]
I think I know where this issue is coming from.

**Comment by ghost** [comment]
This issue has been located and being fixed properly!
