### ISSUE TITLE
[Mobile] Badges not displayed correctly next to posts

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#51]
Badges are not aligned well on mobile devices next to posts. This may be happening because of  eb98382 or a330683.

![screenshot_2018-07-25 flightsimtr - havacilik forumu 1](https://user-images.githubusercontent.com/17576065/43169197-e0287dca-8fa8-11e8-8702-7320add7ca1c.png)

**Comment by ghost** [comment]
This actually may be happening because, of a piece of CSS to fix the badges to close to each other on the Users Profile page. This was addressed last night.

**Comment by ardacebi** [comment]
Already mentioned at the description:

> This may be happening because of eb98382 or a330683.

**Comment by ghost** [comment]
Yes however, that wasnt the CSS I added yesterday to fix badges on the Profile page. The badges arent aligned like that because, of a `background:` tag.

**Comment by ghost** [comment]
Priority was set to Medium as this doesn't cause any issue with the user being able to click on things.

**Comment by ardacebi** [comment]
Told you not to manually close issues if you have a PR open.

**Comment by ghost** [comment]
Use the current code from the Development branch for your Forum as it's fine on that branch, I'll test Stable and see if it's occurring there.

**Comment by ghost** [comment]
This issue seems to be fixed on the Stable and Development branch.

**Comment by ghost** [comment]
This was only fixed on Desktop, I will make sure to add it to the list for Mobile Optimizations.

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.
