### ISSUE TITLE
Naughty icon

### ISSUE THREAD

**Issue by ghost** [Extum/material#69]
They look elegant, but they don't look so good on the mobile side. Like these naughty icons, this also exists in the demo site.
![qrZhp.jpg](https://piccdn.freejishu.com/images/2018/07/26/qrZhp.jpg)
![qrX2A.jpg](https://piccdn.freejishu.com/images/2018/07/26/qrX2A.jpg)

**Comment by ardacebi** [comment]
Thank you for opening this issue @yiveco. We're already aware of mobile optimization issues (#24) and the badge bug (#51) and not guaranteeing mobile support in any way on our theme.

We will be focusing on fixing mobile issues on 1.0.0-beta.4 or 1.0.0-beta.5 as we're currently focused on replacing all components with Material ones and all the testing is done on desktop environments.

But if you're good at CSS and think you can help us with the mobile issues, always feel free to open a PR.

Though, I'm seeing the icon issue on the discussion list for the first time, thanks for that. Can you open another issue for that icon bug, so I'll close this and leave that open?

**Comment by ghost** [comment]
> not guaranteeing mobile support in any way on our theme.

That's untrue, I am working on making this Theme compatible with Desktop/Laptop and Mobile devices currently. I'll check my code on my Community and compare to some code here to see how I fixed it.

**Comment by ghost** [comment]
Please update to the latest Stable release and this should be fixed on your Forum, if you wanna use the Development branch code go right ahead as that has more features currently.
