### ISSUE TITLE
Focused issue on some buttons

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#7]
If you hold clicked on the new discussion button, you will see that it will have a nice material effect with a filter on it. Some buttons such as the buttons on the top right don’t have this effect and they should.

![screenshot_2018-07-23 flightsimtr - havacilik forumu 2](https://user-images.githubusercontent.com/17576065/43087399-7a3d4f28-8ea8-11e8-9c04-2143ffe365e8.png)

**Comment by ghost** [comment]
Are you talking about when certain buttons are pressed and have a Transparent background to them?

**Comment by ardacebi** [comment]
Yes

**Comment by ghost** [comment]
I could possibly fix that.

**Comment by ardacebi** [comment]
I would be so happy to see this fixed because it's so annoying!

I'm working on new features now so that's why I'm not fixing these.

**Comment by ghost** [comment]
No problem.

**Comment by ardacebi** [comment]
Can't you just apply the same style as the IndexPage-newDiscussion or notification button to those buttons?

They already work :)
