### ISSUE TITLE
[Mobile] Composer minimize icon not visible

### ISSUE THREAD

**Issue by daaniiieel** [Extum/material#70]
**Describe the bug**
The minimize (-) icon is not showing correctly on mobile devices

**To Reproduce**
1. Go to the test forum on mobile
2. Click on any topic
3. Scroll down to reply& start writing

**Expected behavior**
A minimize (-) icon needs to appear.

**Screenshots**
![2018-07-26-165612_1680x1050_scrot](https://user-images.githubusercontent.com/41679054/43270228-d70f8f2e-90f4-11e8-846b-ea2dad0ce6da.png)

**Environment (please complete the following information):**
 - OS: Raspbian Jessie && Android 6.0
 - Browser: Vivaldi (Chromium distro)& Opera
 

**Additional context**
Appears on Chromium "emulator" and on Android too

**Comment by TurboProgramming** [comment]
I'm on it. Thank you for the issue @valaki52.

**Comment by ghost** [comment]
I can see what I can do, however I even tried this on the Amplify Community and it didn't work.
