### ISSUE TITLE
Icon Issue

### ISSUE THREAD

**Issue by ghost** [Extum/material#71]
When trying to use the icon unicode code, `e8b6`, it doesn't display...

**Comment by ghost** [comment]
It appears like it is a more serious issue.... When in the inspector, and I try to change a button or something like that, I use the following code:
```<!-- FAB button with ripple -->
<button class="mdl-button mdl-js-button mdl-button--fab mdl-js-ripple-effect">
  <i class="material-icons">add</i>
</button>
```

The button just goes to a straight html button with no styling and a plus sign in the center.... possibly an issue with the forum not importing the actual material design stylesheet?

**Comment by ardacebi** [comment]
@PartialDevAdmin Can you give me more details about this?

**Comment by ghost** [comment]
Your theme does not import the stylesheet from https://getmdl.io, so any custom settings, classes, etc. have to be manually entered in the `material.css` file...

**Comment by ardacebi** [comment]
I will add it later.
