### ISSUE TITLE
Badge pop-up stays inside the button

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#74]
**Describe the bug**
The notification badge when there is a notification stays inside the button area instead of expanding and overlapping the outline button.

**Expected behavior**
The badge should not stay inside the button.

**Screenshots**
![screenshot_2018-07-27 extum material theme demo 1](https://user-images.githubusercontent.com/17576065/43310535-7c6763de-9190-11e8-8ac8-7ceaa1f8473a.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Url: https://materialtheme.freeflarum.com/
 - Flarum Version 0.1.0-beta.7

**Comment by ghost** [comment]
This is a Core issue and Extum does't fix those.

**Comment by ardacebi** [comment]
@Nathan2023 This is not a core issue, the core even doesn't have a border around the original button and the badge overrides the button border, so it works on the core.

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12. **Badges will not be modified as this one was to prevent this from happening.**
