### ISSUE TITLE
[Dark Mode] Colors need enhancements

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#89]
**Describe the bug**
With dark mode enabled, the admin dashboard colors look a bit messed up.

**To Reproduce**
1. Go to admin panel
2. See error

**Expected behavior**
The sidebar background color should be darker.

**Screenshots**
![screenshot_2018-07-28 extum material theme demo 1](https://user-images.githubusercontent.com/17576065/43356415-0a832ac0-9279-11e8-8840-c7a83e325149.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version 0.1.0-beta.7

**Comment by ardacebi** [comment]
I'm changing this issue to general enhancements for dark mode.

**Comment by ardacebi** [comment]
...and I will be working on it.

**Comment by ghost** [comment]
I can work on this issue as of now.

**Comment by ghost** [comment]
The background issue is fixed, however I cant seem to fix the Label problem, it seems to be more of a Core bug?

**Comment by ardacebi** [comment]
Wdym by label problem?

**Comment by ghost** [comment]
What happens is when the one is active in dark mode, the title of what is active along with the icon, is dark instead of a seen color so it mostly blends in.
