### ISSUE TITLE
[Colored Header] Search bar converts to old one

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#92]
**Describe the bug**
If using the colored header option, the search bar at the top (FormControl) switches to the old design for some reason.

**To Reproduce**
1. Go to homepage
2. See error

**Expected behavior**
The search bar should stay Material.

**Screenshots**
![screenshot_2018-07-28 extum material theme demo 4](https://user-images.githubusercontent.com/17576065/43356503-45c23b34-927a-11e8-974f-57957d477788.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version 0.1.0-beta.7

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.

This is expected to be fixed even if the issue hasn't occurred.
