### ISSUE TITLE
Permissions page icons should be Vertically Aligned

### ISSUE THREAD

**Issue by ardacebi** [Extum/material#94]
**Describe the bug**
Icons inside the badges at the permissions page should be centered like others.

**To Reproduce**
1. Go to admin panel
2. Click on permissions
3. Scroll down to badges

**Expected behavior**
The icons should be centered inside badges.

**Screenshots**
![screenshot_2018-07-28 extum material theme demo 7](https://user-images.githubusercontent.com/17576065/43356561-6ed18146-927b-11e8-9c26-17ca01a4df8c.png)

**Environment (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Firefox
 - Flarum Version 0.1.0-beta.7

**Comment by ghost** [comment]
Found a fix. Opening PR now.

**Comment by ardacebi** [comment]
#99 didn't fix this.

**Comment by ghost** [comment]
Are you sure about that? It's a very small difference.

**Comment by ardacebi** [comment]
![screenshot_2018-07-29 extum material theme demo 2](https://user-images.githubusercontent.com/17576065/43361282-8372ad66-92d3-11e8-9335-a4f916df11b0.png)

From the demo server.

**Comment by ardacebi** [comment]
It's basically the same. The thing here is to make these centered. Not with numbers and paddings.

**Comment by ghost** [comment]
The only way to fix things is Padding half of the time. They need to be Vertically Centered which can really only be fixed with a small amount of Padding which I added.

**Comment by ardacebi** [comment]
Okay, then use padding.

**Comment by ghost** [comment]
I did. But, of course when I try to fix something, a file isn't valid or it just won't work.

**Comment by ardacebi** [comment]
Hooray! This is back!

![screenshot_2018-08-11 extum material theme demo](https://user-images.githubusercontent.com/17576065/43983060-618f7214-9d01-11e8-8332-dde5ea24221a.png)

**Comment by ghost** [comment]
Ill take a look.

**Comment by ghost** [comment]
Fixed for the next version!
