### ISSUE TITLE
[Mobile] Drawer notification icon problem

### ISSUE THREAD

**Issue by daaniiieel** [Extum/material#97]
**Describe the bug**
If you open the forum in mobile, you can see, the notifications icon (and card) is wrong-sized

**To Reproduce**
1. Go to the test forum on mobile
2. Click on Log In
3. After Logging in, expand the drawer

**Expected behavior**
The notifications section's card looks normal

**Screenshots**
![materialtheme freeflarum com_ galaxy note ii](https://user-images.githubusercontent.com/41679054/43358395-48a5d164-9291-11e8-9c48-784df0877c90.png)

**Environment (please complete the following information):**
 - OS: Windows 10 Home && Android
 - Browser: Opera
 - Flarum Url: materialtheme.freeflarum.com

**Comment by ghost** [comment]
I know this issue and I was working on it yesterday until I then noticed it wasn't compatible with Desktop and I am working on a hard fix. Unfortunately I for some reason cant use another `@media` in our CSS because, it won't work, and even if I don't that wont work either.

**Comment by ardacebi** [comment]
Wait, can you try using @media again? The time it wasn't working we were using the custom header update techniqe that caused the style file not to compile using Flarum's compiler.

Can you try using @media now and update the install on your localhost from the dev channel? It will get updated with every new commit. (Not beta 1, the dev one)

**Comment by ghost** [comment]
Sure.

**Comment by ardacebi** [comment]
New branch please, PR not necessary.

**Comment by ghost** [comment]
Guess what. This has been fixed for Mobile Optimization however not for Tablet, Laptop, or Desktop. It will be released in `1.0.0-beta.5`

**Comment by hammerhai** [comment]
Issues being closed since this is an incompatible version. A new one will be created if it reoccurs in 0.1.0-beta.12.

All PRs will be tested on all devices before merging unless it known that it does not present major layout changes.
